channels:
  - conda-forge
dependencies:
  - qe>=7.4
  - python=3.9
  - pip
  - aiida-core~=2.5.0
  - xmltodict
  - jupyterlab=3
  - jupyterlab-myst
  - myst-parser~=3.0
  - myst-nb~=1.0
  - sphinx-design
  - sphinx-book-theme
  - sphinx-subfigure>=0.2.4
  - seekpath
